Repository Clo-fi/Running-planet-server, pull requests merged in 2024-05, with the labels that each got.

#6 이슈 템플릿 작성
  .github /ISSUE_TEMPLATE/기능개발.md
Labels: documentation

#7 이슈 템플릿 작성
  .github /ISSUE_TEMPLATE/기능개발.md
Labels: documentation

#9 기본 엔티티 작성
  src/main/java/clofi/runningplanet/board/domain/Board.java
  src/main/java/clofi/runningplanet/board/domain/BoardImage.java
  src/main/java/clofi/runningplanet/board/domain/Comment.java
  src/main/java/clofi/runningplanet/board/domain/ThumbsUp.java
  src/main/java/clofi/runningplanet/common/domain/BaseEntity.java
  src/main/java/clofi/runningplanet/crew/domain/ApprovalType.java
  src/main/java/clofi/runningplanet/crew/domain/Category.java
  src/main/java/clofi/runningplanet/crew/domain/Chat.java
  src/main/java/clofi/runningplanet/crew/domain/Crew.java
  src/main/java/clofi/runningplanet/crew/domain/Tag.java
  src/main/java/clofi/runningplanet/member/domain/Gender.java
  src/main/java/clofi/runningplanet/member/domain/Member.java
  src/main/java/clofi/runningplanet/member/domain/OAuthType.java
  src/main/java/clofi/runningplanet/member/domain/SocialLogin.java
Labels: enhancement

#20 크루 생성 기능
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/Crew.java
  src/main/java/clofi/runningplanet/crew/domain/Tag.java
  src/main/java/clofi/runningplanet/crew/dto/request/CreateCrewReqDto.java
  src/main/java/clofi/runningplanet/crew/dto/request/RuleReqDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewRepository.java
  src/main/java/clofi/runningplanet/crew/repository/TagRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#19 feat. 게시글 작성
  build.gradle
  src/main/java/clofi/runningplanet/board/controller/BoardController.java
  src/main/java/clofi/runningplanet/board/domain/Board.java
  src/main/java/clofi/runningplanet/board/domain/BoardImage.java
  src/main/java/clofi/runningplanet/board/dto/CreateBoardRequest.java
  src/main/java/clofi/runningplanet/board/dto/request/CreateBoardRequest.java
  src/main/java/clofi/runningplanet/board/dto/response/BoardResponse.java
  src/main/java/clofi/runningplanet/board/factory/BoardFactory.java
  src/main/java/clofi/runningplanet/board/repository/BoardImageRepository.java
  src/main/java/clofi/runningplanet/board/service/BoardService.java
  src/main/java/clofi/runningplanet/board/service/S3StorageManagerService.java
  src/main/java/clofi/runningplanet/board/service/S3StorageManagerUseCase.java
  src/main/java/clofi/runningplanet/common/config/S3Config.java
  src/test/java/clofi/runningplanet/board/factory/fake/FakeS3StorageManager.java
  src/test/java/clofi/runningplanet/board/service/BoardServiceTest.java
Labels: enhancement

#23 운동 기록 생성 기능
  src/main/java/clofi/runningplanet/running/controller/RecordController.java
  src/main/java/clofi/runningplanet/running/domain/Coordinate.java
  src/main/java/clofi/runningplanet/running/domain/Record.java
  src/main/java/clofi/runningplanet/running/dto/RecordSaveRequest.java
  src/main/java/clofi/runningplanet/running/dto/RecordSaveResponse.java
  src/main/java/clofi/runningplanet/running/repository/CoordinateRepository.java
  src/main/java/clofi/runningplanet/running/repository/RecordRepository.java
  src/main/java/clofi/runningplanet/running/service/RecordService.java
  src/test/java/clofi/runningplanet/running/service/RecordServiceTest.java
Labels: enhancement

#24 Feat 크루 목록 조회 기능
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/Tag.java
  src/main/java/clofi/runningplanet/crew/dto/CrewLeaderDto.java
  src/main/java/clofi/runningplanet/crew/dto/RuleDto.java
  src/main/java/clofi/runningplanet/crew/dto/request/CreateCrewReqDto.java
  src/main/java/clofi/runningplanet/crew/dto/response/FindAllCrewResDto.java
  src/main/java/clofi/runningplanet/crew/repository/TagRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#28 Feat 크루 상세 조회
  src/main/java/clofi/runningplanet/common/controller/ExceptionControllerAdvice.java
  src/main/java/clofi/runningplanet/common/exception/NotFoundException.java
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/dto/response/FindCrewResDto.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#32 소셜 로그인 기능(카카오)
  build.gradle
  src/main/java/clofi/runningplanet/crew/domain/CrewMember.java
  src/main/java/clofi/runningplanet/member/controller/MemberController.java
  src/main/java/clofi/runningplanet/member/domain/SocialLogin.java
  src/main/java/clofi/runningplanet/member/dto/CustomOAuth2User.java
  src/main/java/clofi/runningplanet/member/dto/KakaoResponse.java
  src/main/java/clofi/runningplanet/member/dto/OAuth2Response.java
  src/main/java/clofi/runningplanet/member/repository/MemberRepository.java
  src/main/java/clofi/runningplanet/member/repository/SocialLoginRepository.java
  src/main/java/clofi/runningplanet/member/service/MemberService.java
  src/main/java/clofi/runningplanet/security/config/CorsMvcConfig.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
  src/main/java/clofi/runningplanet/security/jwt/JWTFilter.java
  src/main/java/clofi/runningplanet/security/jwt/JWTUtil.java
  src/main/java/clofi/runningplanet/security/jwt/JwtToken.java
  src/main/java/clofi/runningplanet/security/oauth2/CustomSuccessHandler.java
Labels: enhancement

#36 토큰 경로 수정(헤더->쿠키)
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
  src/main/java/clofi/runningplanet/security/jwt/JWTFilter.java
  src/main/java/clofi/runningplanet/security/oauth2/CustomSuccessHandler.java
Labels: enhancement

#40 로그인 데이터 중복 저장 수정
  src/main/java/clofi/runningplanet/member/domain/SocialLogin.java
  src/main/java/clofi/runningplanet/member/repository/SocialLoginRepository.java
  src/main/java/clofi/runningplanet/member/service/MemberService.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
  src/main/java/clofi/runningplanet/security/jwt/JWTFilter.java
Labels: bug

#41 운동 기록 조회 기능
  src/main/java/clofi/runningplanet/running/controller/RecordController.java
  src/main/java/clofi/runningplanet/running/domain/Record.java
  src/main/java/clofi/runningplanet/running/dto/AvgPaceResponse.java
  src/main/java/clofi/runningplanet/running/dto/CoordinateResponse.java
  src/main/java/clofi/runningplanet/running/dto/RecordFindAllResponse.java
  src/main/java/clofi/runningplanet/running/dto/RecordFindCurrentResponse.java
  src/main/java/clofi/runningplanet/running/dto/RecordFindResponse.java
  src/main/java/clofi/runningplanet/running/dto/RunTimeResponse.java
  src/main/java/clofi/runningplanet/running/repository/CoordinateRepository.java
  src/main/java/clofi/runningplanet/running/repository/RecordRepository.java
  src/main/java/clofi/runningplanet/running/service/RecordService.java
  src/test/java/clofi/runningplanet/running/service/RecordServiceTest.java
Labels: enhancement

#43 Feat 크루 신청 기능
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/Approval.java
  src/main/java/clofi/runningplanet/crew/domain/CrewApplication.java
  src/main/java/clofi/runningplanet/crew/dto/request/ApplyCrewReqDto.java
  src/main/java/clofi/runningplanet/crew/dto/response/ApplyCrewResDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewApplicationRepository.java
  src/main/java/clofi/runningplanet/crew/repository/CrewMemberRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/board/core/service/BoardReadServiceTest.java
Labels: enhancement

#48 Feat: http exception 정의
  src/main/java/clofi/runningplanet/common/controller/ExceptionControllerAdvice.java
  src/main/java/clofi/runningplanet/common/exception/BadRequestException.java
  src/main/java/clofi/runningplanet/common/exception/ConflictException.java
  src/main/java/clofi/runningplanet/common/exception/ForbiddenException.java
  src/main/java/clofi/runningplanet/common/exception/UnauthorizedException.java
Labels: enhancement

#49 CORS 관련 쿠키 설정 및 유저 검증 관련 ID 추가
  src/main/java/clofi/runningplanet/member/dto/CustomOAuth2User.java
  src/main/java/clofi/runningplanet/member/service/MemberService.java
  src/main/java/clofi/runningplanet/security/config/CorsMvcConfig.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
  src/main/java/clofi/runningplanet/security/oauth2/CustomSuccessHandler.java
Labels: enhancement

#53 운동 기능에 회원 로직 추가
  src/main/java/clofi/runningplanet/running/controller/RecordController.java
  src/main/java/clofi/runningplanet/running/domain/Record.java
  src/main/java/clofi/runningplanet/running/dto/RecordSaveRequest.java
  src/main/java/clofi/runningplanet/running/dto/RecordSaveResponse.java
  src/main/java/clofi/runningplanet/running/repository/RecordRepository.java
  src/main/java/clofi/runningplanet/running/service/RecordService.java
  src/test/java/clofi/runningplanet/running/service/RecordServiceTest.java
Labels: enhancement

#54 build: 접근 권한 추가
  .github/workflows/dev-ci-cd.yml
Labels: bug

#58 Feat: 크루 생성 기능에 회원 로직 추가
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/Crew.java
  src/main/java/clofi/runningplanet/crew/domain/CrewMember.java
  src/main/java/clofi/runningplanet/crew/dto/request/CreateCrewReqDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewMemberRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/common/WithMockCustomMember.java
  src/test/java/clofi/runningplanet/common/WithMockCustomMemberSecurityContextFactory.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#57 Feat/#46 좋아요 기능 추가
  src/main/java/clofi/runningplanet/board/comment/controller/CommentController.java
  src/main/java/clofi/runningplanet/board/core/dto/response/BoardResponse.java
  src/main/java/clofi/runningplanet/board/core/repository/ThumbsUpRepository.java
  src/main/java/clofi/runningplanet/board/core/service/BoardQueryService.java
  src/main/java/clofi/runningplanet/board/core/service/BoardReadService.java
  src/main/java/clofi/runningplanet/board/thumbsUp/controller/ThumbsUpController.java
  src/main/java/clofi/runningplanet/board/thumbsUp/repository/ThumbsUpRepository.java
  src/main/java/clofi/runningplanet/board/thumbsUp/service/ThumbsUpService.java
  src/test/java/clofi/runningplanet/board/thumbsUp/service/ThumbsUpServiceTest.java
Labels: enhancement

#59 feat. 프로필 조회 기능
  src/main/java/clofi/runningplanet/crew/domain/CrewMember.java
  src/main/java/clofi/runningplanet/member/controller/MemberController.java
  src/main/java/clofi/runningplanet/member/dto/ProfileResponse.java
  src/main/java/clofi/runningplanet/member/service/MemberService.java
  src/test/java/clofi/runningplanet/member/service/MemberServiceTest.java
Labels: enhancement

#65 프로필 조회 테스트 코드 수정
  src/main/java/clofi/runningplanet/crew/domain/CrewMember.java
  src/test/java/clofi/runningplanet/member/service/MemberServiceTest.java
Labels: bug

#66 Feat: 크루 조회 기능 유저 로직 추가
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#68 미인증 요청 시 OAuth flow 진행하는 문제 수정
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
Labels: bug

#74 로그인 응답 방식 변경
  src/main/java/clofi/runningplanet/security/config/CorsMvcConfig.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
  src/main/java/clofi/runningplanet/security/jwt/JWTFilter.java
  src/main/java/clofi/runningplanet/security/oauth2/CustomSuccessHandler.java
Labels: enhancement

#71 Feat: 크루 신청 기능 유저로직 추가
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/Crew.java
  src/main/java/clofi/runningplanet/crew/domain/CrewApplication.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewApplicationTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#75 Feat: 크루 가입 신청 목록 조회
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/CrewMember.java
  src/main/java/clofi/runningplanet/crew/dto/response/ApprovalMemberResDto.java
  src/main/java/clofi/runningplanet/crew/dto/response/GetApplyCrewResDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewApplicationRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewMemberTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#77 프로필 수정 기능
  src/main/java/clofi/runningplanet/board/core/factory/BoardFactory.java
  src/main/java/clofi/runningplanet/board/core/service/BoardQueryService.java
  src/main/java/clofi/runningplanet/common/service/S3StorageManagerService.java
  src/main/java/clofi/runningplanet/common/service/S3StorageManagerUseCase.java
  src/main/java/clofi/runningplanet/member/controller/MemberController.java
  src/main/java/clofi/runningplanet/member/domain/Member.java
  src/main/java/clofi/runningplanet/member/dto/request/UpdateProfileRequest.java
  src/main/java/clofi/runningplanet/member/dto/response/KakaoResponse.java
  src/main/java/clofi/runningplanet/member/dto/response/OAuth2Response.java
  src/main/java/clofi/runningplanet/member/dto/response/ProfileResponse.java
  src/main/java/clofi/runningplanet/member/dto/response/UpdateProfileResponse.java
  src/main/java/clofi/runningplanet/member/service/MemberService.java
  src/test/java/clofi/runningplanet/board/core/service/BoardQueryServiceTest.java
  src/test/java/clofi/runningplanet/common/FakeS3StorageManager.java
  src/test/java/clofi/runningplanet/member/service/MemberServiceTest.java
Labels: enhancement

#78 Feat: 크루 승인 거절 기능
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/Approval.java
  src/main/java/clofi/runningplanet/crew/domain/Crew.java
  src/main/java/clofi/runningplanet/crew/domain/CrewApplication.java
  src/main/java/clofi/runningplanet/crew/domain/CrewMember.java
  src/main/java/clofi/runningplanet/crew/dto/request/ProceedApplyReqDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewMemberRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewApplicationTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#82 refactor. 개인프로필 조회 기능 CrewId 반환 코드 및 테스트 코드 수정
  src/main/java/clofi/runningplanet/member/dto/response/SelfProfileResponse.java
  src/test/java/clofi/runningplanet/member/service/MemberServiceTest.java
Labels: bug

#83 Feat: 크루원 강퇴
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/repository/CrewMemberRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#87 Feat: 크루 탈퇴
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#92 멤버 도메인관련 필드 타입 수정
  src/main/java/clofi/runningplanet/member/domain/Member.java
  src/main/java/clofi/runningplanet/member/dto/response/ProfileResponse.java
  src/main/java/clofi/runningplanet/member/dto/response/SelfProfileResponse.java
Labels: bug, enhancement

#97 추가정보 등록 기능 추가
  src/main/java/clofi/runningplanet/member/controller/MemberController.java
  src/main/java/clofi/runningplanet/member/domain/Member.java
  src/main/java/clofi/runningplanet/member/dto/request/CreateOnboardingRequest.java
  src/main/java/clofi/runningplanet/member/service/MemberService.java
  src/test/java/clofi/runningplanet/member/service/MemberServiceTest.java
Labels: enhancement

#98 Feat: 크루 가입 신청 취소
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/CrewApplication.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewApplicationTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#102 카카오 로그인 요청에 프록시 적용
  src/main/java/clofi/runningplanet/security/config/OAuthProxyConfig.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
Labels: enhancement

#103 proxy host 이름 수정
  src/main/java/clofi/runningplanet/security/config/OAuthProxyConfig.java
Labels: bug

#104 Access token null로 받아지는 문제 수정
  src/main/java/clofi/runningplanet/security/config/OAuthProxyConfig.java
Labels: bug

#105 AccessToken으로 유저 정보 가져올 때도 프록시 적용하게 변경
  src/main/java/clofi/runningplanet/security/config/OAuthProxyConfig.java
Labels: bug

#107 user info endpoint 요청 시 프록시 적용되지 않는 문제 수정
  src/main/java/clofi/runningplanet/member/service/MemberService.java
  src/main/java/clofi/runningplanet/security/config/OAuthProxyConfig.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
Labels: bug

#109 feat: 운영 환경 별 logging 설정 추가
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: enhancement
