Repository Clo-fi/Running-planet-server, pull requests merged in 2024-07, with the labels that each got.

#197 소셜로그인 method 수정
  src/main/java/clofi/runningplanet/member/controller/MemberController.java
Labels: bug, enhancement

#198 README 작성
  README.md
  images/architecture.png
  images/icon-512x512.png
  images/img1.png
  images/img2.png
  images/img3.png
  images/img4.png
Labels: documentation

#202 Feat : 크루 신청 목록 조회에서 승인/거부 인원도 조회되는 문제 수정
  src/main/java/clofi/runningplanet/crew/repository/CrewApplicationRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
  src/test/java/clofi/runningplanet/crew/service/integration/CrewServiceIntegrationTest.java
Labels: bug
