Repository Clo-fi/Running-planet-server, pull requests merged in 2024-06, with the labels that each got.

#110 SocialLogin find시 Member fetch join 적용
  src/main/java/clofi/runningplanet/member/repository/SocialLoginRepository.java
  src/main/java/clofi/runningplanet/member/service/MemberService.java
Labels: enhancement

#118 카카오 로그인 컨트롤러 추가
  src/main/java/clofi/runningplanet/member/controller/MemberController.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
Labels: enhancement

#119 로그인 관련 코드 수정
  src/main/java/clofi/runningplanet/member/controller/MemberController.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
Labels: bug

#120 fix. 테스트를 위한 corsConfig 삭제
  src/main/java/clofi/runningplanet/security/config/CorsMvcConfig.java
Labels: bug

#115 웹소켓 설정 추가
  src/main/java/clofi/runningplanet/socket/StompHandler.java
  src/main/java/clofi/runningplanet/socket/WebSocketConfig.java
Labels: enhancement

#121 Feat 크루 요구사항 변경 반영
  src/main/java/clofi/runningplanet/common/service/S3StorageManagerService.java
  src/main/java/clofi/runningplanet/common/service/S3StorageManagerUseCase.java
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/Crew.java
  src/main/java/clofi/runningplanet/crew/domain/CrewImage.java
  src/main/java/clofi/runningplanet/crew/dto/request/CreateCrewReqDto.java
  src/main/java/clofi/runningplanet/crew/dto/response/FindAllCrewResDto.java
  src/main/java/clofi/runningplanet/crew/dto/response/FindCrewResDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewImageRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/board/comment/service/CommentServiceTest.java
  src/test/java/clofi/runningplanet/board/core/service/BoardQueryServiceTest.java
  src/test/java/clofi/runningplanet/board/core/service/BoardReadServiceTest.java
  src/test/java/clofi/runningplanet/board/thumbsUp/service/ThumbsUpServiceTest.java
  src/test/java/clofi/runningplanet/common/FakeS3StorageManager.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewMemberTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
  src/test/java/clofi/runningplanet/member/service/MemberServiceTest.java
Labels: enhancement

#125 feat: 카카오 로그인 spring security -> restTemplate
  src/main/java/clofi/runningplanet/member/controller/MemberController.java
  src/main/java/clofi/runningplanet/member/dto/OauthToken.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
Labels: enhancement

#128 Feat : 크루 정보 수정
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/Crew.java
  src/main/java/clofi/runningplanet/crew/domain/CrewImage.java
  src/main/java/clofi/runningplanet/crew/domain/Tag.java
  src/main/java/clofi/runningplanet/crew/dto/request/UpdateCrewReqDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewImageRepository.java
  src/main/java/clofi/runningplanet/crew/repository/TagRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#131 운동 현황 조회 소켓 API 구현
  src/main/java/clofi/runningplanet/running/dto/RunningStatusResponse.java
  src/main/java/clofi/runningplanet/running/service/RecordService.java
  src/main/java/clofi/runningplanet/security/config/CorsMvcConfig.java
  src/main/java/clofi/runningplanet/security/config/SecurityConfig.java
  src/main/java/clofi/runningplanet/socket/StompHandler.java
  src/main/java/clofi/runningplanet/socket/WebSocketConfig.java
Labels: enhancement

#132 채팅 기능 구현
  src/main/java/clofi/runningplanet/crew/domain/Chat.java
  src/main/java/clofi/runningplanet/crew/repository/ChatRepository.java
  src/main/java/clofi/runningplanet/member/repository/MemberRepository.java
  src/main/java/clofi/runningplanet/socket/controller/SocketController.java
  src/main/java/clofi/runningplanet/socket/dto/response/ChatMessage.java
  src/main/java/clofi/runningplanet/socket/dto/response/DataResponse.java
  src/main/java/clofi/runningplanet/socket/service/SocketService.java
Labels: enhancement

#138 Feat: 크루 미션 조회
  src/main/java/clofi/runningplanet/common/controller/ExceptionControllerAdvice.java
  src/main/java/clofi/runningplanet/common/exception/InternalServerException.java
  src/main/java/clofi/runningplanet/crew/repository/CrewMemberRepository.java
  src/main/java/clofi/runningplanet/mission/controller/MissionController.java
  src/main/java/clofi/runningplanet/mission/domain/CrewMission.java
  src/main/java/clofi/runningplanet/mission/domain/MissionType.java
  src/main/java/clofi/runningplanet/mission/dto/response/CrewMissionListDto.java
  src/main/java/clofi/runningplanet/mission/dto/response/GetCrewMissionResDto.java
  src/main/java/clofi/runningplanet/mission/repository/CrewMissionRepository.java
  src/main/java/clofi/runningplanet/mission/service/MissionService.java
  src/main/java/clofi/runningplanet/running/repository/RecordRepository.java
  src/test/java/clofi/runningplanet/common/TestHelper.java
  src/test/java/clofi/runningplanet/mission/controller/MissionControllerTest.java
  src/test/java/clofi/runningplanet/mission/service/MissionServiceTest.java
Labels: enhancement

#134 feat.행성조회
  src/main/java/clofi/runningplanet/board/core/dto/response/BoardDetailResponse.java
  src/main/java/clofi/runningplanet/board/core/service/BoardReadService.java
  src/main/java/clofi/runningplanet/crew/dto/response/GetApplyCrewResDto.java
  src/main/java/clofi/runningplanet/member/domain/Member.java
  src/main/java/clofi/runningplanet/member/dto/response/ProfileResponse.java
  src/main/java/clofi/runningplanet/member/dto/response/SelfProfileResponse.java
  src/main/java/clofi/runningplanet/planet/controller/PlanetController.java
  src/main/java/clofi/runningplanet/planet/domain/MemberPlanet.java
  src/main/java/clofi/runningplanet/planet/domain/Planet.java
  src/main/java/clofi/runningplanet/planet/dto/response/PlanetResponse.java
  src/main/java/clofi/runningplanet/planet/repository/MemberPlanetRepository.java
  src/main/java/clofi/runningplanet/planet/repository/PlanetRepository.java
  src/main/java/clofi/runningplanet/planet/service/PlanetService.java
  src/test/java/clofi/runningplanet/RunningMemberPlanetApplicationTests.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewMemberTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
  src/test/java/clofi/runningplanet/member/service/MemberServiceTest.java
  src/test/java/clofi/runningplanet/planet/service/PlanetServiceTest.java
  src/test/java/clofi/runningplanet/running/service/RecordServiceTest.java
Labels: enhancement

#145 Feat : 크루 미션 완료
  src/main/java/clofi/runningplanet/crew/domain/Crew.java
  src/main/java/clofi/runningplanet/crew/dto/response/FindAllCrewResDto.java
  src/main/java/clofi/runningplanet/crew/dto/response/FindCrewResDto.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/main/java/clofi/runningplanet/mission/controller/MissionController.java
  src/main/java/clofi/runningplanet/mission/domain/CrewMission.java
  src/main/java/clofi/runningplanet/mission/domain/MissionType.java
  src/main/java/clofi/runningplanet/mission/domain/vo/TodayRecords.java
  src/main/java/clofi/runningplanet/mission/service/MissionService.java
  src/test/java/clofi/runningplanet/common/TestHelper.java
  src/test/java/clofi/runningplanet/crew/domain/CrewMemberTest.java
  src/test/java/clofi/runningplanet/crew/domain/CrewTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
  src/test/java/clofi/runningplanet/mission/controller/MissionControllerTest.java
  src/test/java/clofi/runningplanet/mission/domain/MissionTypeTest.java
  src/test/java/clofi/runningplanet/mission/service/MissionServiceTest.java
Labels: enhancement

#143 feat. 행성 이름 수정
  src/main/java/clofi/runningplanet/board/core/dto/response/BoardDetailResponse.java
  src/main/java/clofi/runningplanet/planet/controller/PlanetController.java
  src/main/java/clofi/runningplanet/planet/domain/MemberPlanet.java
  src/main/java/clofi/runningplanet/planet/dto/request/UpdatePlanetNameRequest.java
  src/main/java/clofi/runningplanet/planet/service/PlanetService.java
  src/test/java/clofi/runningplanet/planet/service/PlanetServiceTest.java
Labels: enhancement

#146 운동 현황 목록 조회
  src/main/java/clofi/runningplanet/common/utils/TimeUtils.java
  src/main/java/clofi/runningplanet/crew/repository/CrewMemberRepository.java
  src/main/java/clofi/runningplanet/running/controller/RecordController.java
  src/main/java/clofi/runningplanet/running/domain/Record.java
  src/main/java/clofi/runningplanet/running/repository/RecordRepository.java
  src/main/java/clofi/runningplanet/running/service/RecordService.java
  src/test/java/clofi/runningplanet/running/service/RecordServiceTest.java
Labels: bug, enhancement

#149 프로필 이미지를 변경하지 않아도 프로필 수정 가능
  src/main/java/clofi/runningplanet/member/service/MemberService.java
Labels: bug, enhancement

#153 기존 채팅 불러오기 테스트 코드 수정
  src/test/java/clofi/runningplanet/chat/service/ChatServiceTest.java
Labels: bug

#150 Feat : 크루 페이지 조회
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/CrewImage.java
  src/main/java/clofi/runningplanet/crew/dto/response/FindCrewWithMissionResDto.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/main/java/clofi/runningplanet/mission/repository/CrewMissionRepository.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#156 본인 프로필 조회시 memberId 추가하여 반환
  src/main/java/clofi/runningplanet/member/dto/response/SelfProfileResponse.java
Labels: enhancement

#157 운동 현황 목록 조회 추가 요구사항 반영
  src/main/java/clofi/runningplanet/running/dto/RunningStatusResponse.java
  src/main/java/clofi/runningplanet/running/service/RecordService.java
  src/test/java/clofi/runningplanet/running/service/RecordServiceTest.java
Labels: enhancement

#158 Feat : 크루 변경사항 반영
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/dto/response/GetApplyCrewResDto.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/main/java/clofi/runningplanet/mission/domain/CrewMission.java
  src/main/java/clofi/runningplanet/mission/repository/CrewMissionRepository.java
  src/main/java/clofi/runningplanet/mission/service/MissionService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
  src/test/java/clofi/runningplanet/mission/service/MissionServiceTest.java
Labels: bug, enhancement

#163 feat: 크루 페이지 조회 응답에 crewId 추가
  src/main/java/clofi/runningplanet/crew/dto/response/FindCrewWithMissionResDto.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
Labels: enhancement

#167 Feat : 개발 서버 로그 설정 추가
  .github/workflows/dev-ci-cd.yml
  build.gradle
  src/main/resources/async-discord-appender.xml
  src/main/resources/discord-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: enhancement

#170 feat: 크루 생성 시 크루 미션 초기화 로직 추가
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
Labels: bug

#172 Feat : 크루 명단 조회
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/domain/CrewApplication.java
  src/main/java/clofi/runningplanet/crew/dto/response/FindCrewMemberResDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewMemberRepository.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/main/java/clofi/runningplanet/mission/domain/CrewMission.java
  src/main/java/clofi/runningplanet/mission/repository/CrewMissionRepository.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
Labels: enhancement

#175 fix: 소켓 헤더 접근 방법 수정
  src/main/java/clofi/runningplanet/socket/StompHandler.java
Labels: bug

#176 기존 채팅 불러오기 커서 기반 페이지네이션 적용
  src/main/java/clofi/runningplanet/chat/controller/ChatController.java
  src/main/java/clofi/runningplanet/chat/repository/ChatRepository.java
  src/main/java/clofi/runningplanet/chat/service/ChatService.java
  src/test/java/clofi/runningplanet/chat/service/ChatServiceTest.java
Labels: enhancement

#181 ChatService 테스트 코드 및 dto 수정
  src/main/java/clofi/runningplanet/chat/controller/ChatController.java
  src/main/java/clofi/runningplanet/chat/dto/request/ChatMessageRequest.java
  src/main/java/clofi/runningplanet/chat/dto/response/ChatListResponse.java
  src/main/java/clofi/runningplanet/chat/dto/response/ChatMessageResponse.java
  src/main/java/clofi/runningplanet/chat/repository/ChatRepository.java
  src/main/java/clofi/runningplanet/chat/service/ChatService.java
  src/test/java/clofi/runningplanet/chat/service/ChatServiceTest.java
Labels: bug

#183 운동 완료 시 행성 경험치 및 회원 정보 업데이트
  src/main/java/clofi/runningplanet/member/domain/Member.java
  src/main/java/clofi/runningplanet/member/dto/response/ProfileResponse.java
  src/main/java/clofi/runningplanet/member/dto/response/SelfProfileResponse.java
  src/main/java/clofi/runningplanet/planet/dto/response/PlanetResponse.java
  src/main/java/clofi/runningplanet/planet/service/PlanetService.java
  src/main/java/clofi/runningplanet/running/repository/RecordRepository.java
  src/main/java/clofi/runningplanet/running/service/RecordService.java
  src/test/java/clofi/runningplanet/rank/service/RankServiceTest.java
  src/test/java/clofi/runningplanet/running/service/RecordServiceTest.java
Labels: enhancement

#187 운동 응원 기능
  src/main/java/clofi/runningplanet/crew/repository/CrewMemberRepository.java
  src/main/java/clofi/runningplanet/member/domain/CustomUser.java
  src/main/java/clofi/runningplanet/running/controller/RecordController.java
  src/main/java/clofi/runningplanet/running/domain/Cheer.java
  src/main/java/clofi/runningplanet/running/dto/CheerResponse.java
  src/main/java/clofi/runningplanet/running/dto/RunningStatusFindAllResponse.java
  src/main/java/clofi/runningplanet/running/dto/RunningStatusResponse.java
  src/main/java/clofi/runningplanet/running/repository/CheerRepository.java
  src/main/java/clofi/runningplanet/running/repository/RecordRepository.java
  src/main/java/clofi/runningplanet/running/service/RecordService.java
  src/main/java/clofi/runningplanet/socket/StompHandler.java
  src/test/java/clofi/runningplanet/running/service/RecordServiceTest.java
Labels: enhancement

#185 Feat : 크루 신청 오류 수정 및 테스트 코드
  .github/workflows/dev-ci-cd.yml
  src/main/java/clofi/runningplanet/crew/domain/CrewApplication.java
  src/test/java/clofi/runningplanet/common/DataCleaner.java
  src/test/java/clofi/runningplanet/common/H2DataCleaner.java
  src/test/java/clofi/runningplanet/common/MysqlDataCleaner.java
  src/test/java/clofi/runningplanet/crew/service/integration/CrewServiceIntegrationTest.java
Labels: bug, enhancement

#188 개인 랭킹 조회
  src/main/java/clofi/runningplanet/rank/controller/RankController.java
  src/main/java/clofi/runningplanet/rank/dto/PersonalRankResponse.java
  src/main/java/clofi/runningplanet/rank/repository/PersonalRankRepository.java
  src/main/java/clofi/runningplanet/rank/service/RankService.java
  src/test/java/clofi/runningplanet/rank/service/RankServiceTest.java
Labels: enhancement

#190 Feat : 크루 검색 및 필터링
  src/main/java/clofi/runningplanet/crew/controller/CrewController.java
  src/main/java/clofi/runningplanet/crew/dto/SearchParamDto.java
  src/main/java/clofi/runningplanet/crew/repository/CrewRepository.java
  src/main/java/clofi/runningplanet/crew/repository/CrewRepositoryCustom.java
  src/main/java/clofi/runningplanet/crew/repository/CrewRepositoryImpl.java
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/main/java/clofi/runningplanet/mission/service/MissionService.java
  src/test/java/clofi/runningplanet/crew/controller/CrewControllerTest.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
  src/test/java/clofi/runningplanet/crew/service/integration/CrewServiceIntegrationTest.java
  src/test/java/clofi/runningplanet/mission/service/MissionServiceTest.java
Labels: enhancement

#191 ChatService lastChatTimestamp formatter 삭제
  src/main/java/clofi/runningplanet/chat/service/ChatService.java
Labels: bug

#193 Feat : 크루 미션 변경사항
  src/main/java/clofi/runningplanet/crew/service/CrewService.java
  src/main/java/clofi/runningplanet/mission/domain/MissionType.java
  src/test/java/clofi/runningplanet/crew/service/CrewServiceTest.java
  src/test/java/clofi/runningplanet/crew/service/integration/CrewServiceIntegrationTest.java
  src/test/java/clofi/runningplanet/mission/service/MissionServiceTest.java
  src/test/java/clofi/runningplanet/mission/service/integration/MissionServiceIntegrationTest.java
Labels: bug

#196 Feat : 일일 미션 생성 로직
  src/main/java/clofi/runningplanet/mission/service/MissionService.java
  src/main/java/clofi/runningplanet/scheduler/MissionScheduler.java
  src/test/java/clofi/runningplanet/mission/service/integration/MissionServiceIntegrationTest.java
Labels: enhancement
